version: "3.1"
services:
  webserver:
    image: caddy:2.8.4-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy_data:/data
      - $PWD/caddy_config:/config
    links:
      - api
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
    links:
      - db
    expose:
      - 8080
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: jun2-ish_db
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  pgdata:
  caddy_data:
    external: true
  caddy_config:
